# Generated by Django 5.2 on 2025-04-06 17:10

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="All species have a 'natural' or 'base' look and feel, but, their physical appearance and colours may vary based on environmental factors. Not all species are available in all variants.", max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_variant_name_not_blank', violation_error_message='%(app_label)s %(class)s name must not be blank.'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_variant_name_case_insensitive_unique', violation_error_message='%(app_label)s %(class)s name already exists (case insensitive match).')],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(help_text='What unique term has the great Oneiromancer chosen to refer to this kind of monster?', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('date_discovered', models.DateTimeField(auto_now_add=True, help_text='When did the great Oneiromancer learn about the existence of this species?')),
                ('description', models.TextField(blank=True, help_text='How would the great Oneiromancer describe the behaviours and build of this species? Its nature, its rituals, its way of life?')),
                ('available_variants', models.ManyToManyField(help_text='What variations in physical appearance and colour can this species have?', related_name='species', to='pets.variant')),
            ],
            options={
                'ordering': ['species'],
                'constraints': [models.CheckConstraint(condition=models.Q(('species', ''), _negated=True), name='pets_pet_species_not_blank', violation_error_message='%(app_label)s %(class)s species must not be blank.'), models.UniqueConstraint(django.db.models.functions.text.Lower('species'), name='pets_pet_species_case_insensitive_unique', violation_error_message='%(app_label)s %(class)s species already exists (case insensitive match).')],
            },
        ),
    ]
