# Generated by Django 5.2 on 2025-04-09 08:33

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What unique term has the great Oneiromancer chosen to refer to this species? Letters only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('date_discovered', models.DateTimeField(auto_now_add=True, help_text='When did the great Oneiromancer learn about the existence of this species?')),
                ('description', models.TextField(blank=True, help_text='How would the great Oneiromancer describe the behaviours and build of this species? Its attitude, its rituals, its way of life?')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_species_name_not_blank', violation_error_message='Species name must not be blank.'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_species_name_case_insensitive_unique', violation_error_message='Species name already exists (case insensitive match).')],
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='combinations')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.species')),
            ],
            options={
                'ordering': ['species', 'theme'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="All species have a 'natural' look. Some have different themes i.e. variations in physical appearance and colour. What would you call this style? Letters only.", max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('description', models.TextField(blank=True, help_text='How does this theme (variation in physical appearance and colour) deviate from the natural look of the species?')),
                ('valid_species', models.ManyToManyField(help_text='What species are available in this theme (variation in physical appearance and colour)?', related_name='valid_themes', through='pets.Combination', to='pets.species')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What name has been bestowed upon this blessed pet? Must be unique and cannot be changed. Letters and numbers only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed; no spaces, symbols etc.')])),
                ('date_hatched', models.DateTimeField(auto_now_add=True, help_text='When did this pet hatch?')),
                ('owner', models.ForeignKey(help_text='Who does this pet belong to?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(help_text='What species is this pet?', on_delete=django.db.models.deletion.CASCADE, to='pets.species')),
                ('theme', models.ForeignKey(default=1, help_text='What theme is the pet?', on_delete=django.db.models.deletion.SET_DEFAULT, to='pets.theme')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='combination',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.theme'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_theme_name_not_blank', violation_error_message='Theme name must not be blank.'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_theme_name_case_insensitive_unique', violation_error_message='Theme name already exists (case insensitive match).'),
        ),
        migrations.AddConstraint(
            model_name='petinstance',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_petinstance_name_not_blank', violation_error_message='PetInstance name must not be blank.'),
        ),
        migrations.AddConstraint(
            model_name='petinstance',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_petinstance_name_case_insensitive_unique', violation_error_message='PetInstance name already exists (case insensitive match).'),
        ),
        migrations.AddConstraint(
            model_name='combination',
            constraint=models.UniqueConstraint(fields=('species', 'theme'), name='pets_combination_species_theme_unique_together', violation_error_message='Combination of Species and Theme is not unique together.'),
        ),
    ]
