# Generated by Django 5.2 on 2025-04-07 14:04

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What unique term has the great Oneiromancer chosen to refer to this species?', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('date_discovered', models.DateTimeField(auto_now_add=True, help_text='When did the great Oneiromancer learn about the existence of this species?')),
                ('description', models.TextField(blank=True, help_text='How would the great Oneiromancer describe the behaviours and build of this species? Its attitude, its rituals, its way of life?')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_species_name_not_blank', violation_error_message='species name must not be blank.'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_species_name_case_insensitive_unique', violation_error_message='species name already exists (case insensitive match).')],
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='species_style_combinations')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.species')),
            ],
            options={
                'ordering': ['species', 'style'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('description', models.TextField(blank=True, help_text="All species have a 'natural' look. Some species have a variety of different styles for their physical appearance and colour.")),
                ('valid_species', models.ManyToManyField(help_text='What species are available in this style (variation in physical appearance and colour)?', related_name='valid_styles', through='pets.Combination', to='pets.species')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What name has been bestowed upon this blessed pet? Must be unique and cannot be changed.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')])),
                ('date_discovered', models.DateTimeField(auto_now_add=True, help_text='When did this pet hatch?')),
                ('owner', models.ForeignKey(help_text='Who does this pet belong to?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(help_text='What species is this pet?', on_delete=django.db.models.deletion.CASCADE, to='pets.species')),
                ('style', models.ForeignKey(default=1, help_text='What style is the pet?', on_delete=django.db.models.deletion.SET_DEFAULT, to='pets.style')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='combination',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.style'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_style_name_not_blank', violation_error_message='style name must not be blank.'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_style_name_case_insensitive_unique', violation_error_message='style name already exists (case insensitive match).'),
        ),
        migrations.AddConstraint(
            model_name='petinstance',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_petinstance_name_not_blank', violation_error_message='pet instance name must not be blank.'),
        ),
        migrations.AddConstraint(
            model_name='petinstance',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_petinstance_name_case_insensitive_unique', violation_error_message='pet instance name already exists (case insensitive match).'),
        ),
        migrations.AddConstraint(
            model_name='combination',
            constraint=models.UniqueConstraint(fields=('species', 'style'), name='pets_combination_species_style_unique_together', violation_error_message='combination of species and style is not unique together.'),
        ),
    ]
