# Generated by Django 5.2 on 2025-04-09 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinstance',
            name='date_hatched',
            field=models.DateTimeField(auto_now_add=True, help_text='When did this beloved monster hatch?'),
        ),
        migrations.AlterField(
            model_name='petinstance',
            name='name',
            field=models.CharField(help_text='What name has been bestowed upon this beloved monster? Must be unique and cannot be changed. Letters and numbers only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed; no spaces, symbols etc.')]),
        ),
        migrations.AlterField(
            model_name='petinstance',
            name='owner',
            field=models.ForeignKey(help_text='Who does this beloved monster belong to?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petinstance',
            name='species',
            field=models.ForeignKey(help_text='What species (type of monster) is this pet?', on_delete=django.db.models.deletion.CASCADE, to='pets.species'),
        ),
        migrations.AlterField(
            model_name='petinstance',
            name='theme',
            field=models.ForeignKey(default=1, help_text='What theme (variation in physical appearance and colour) is this pet?', on_delete=django.db.models.deletion.SET_DEFAULT, to='pets.theme'),
        ),
        migrations.AlterField(
            model_name='species',
            name='date_discovered',
            field=models.DateTimeField(auto_now_add=True, help_text='When did the great Oneiromancer learn about the existence of this monster species?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, help_text='How would the great Oneiromancer describe the behaviours and build of this particular monster species? Its attitude, its rituals, its way of life?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='What unique term has the great Oneiromancer chosen to refer to this monster species? Letters only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, help_text='Describe this theme (variation in physical appearance and colour).'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(help_text='Some monster species have different themes i.e. variations in physical appearance and colour. What would you call this theme? Letters only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='valid_species',
            field=models.ManyToManyField(help_text='What monster species are available in this theme (variation in physical appearance and colour)?', related_name='valid_themes', through='pets.Combination', to='pets.species'),
        ),
    ]
