# Generated by Django 5.2 on 2025-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinstance',
            old_name='date_discovered',
            new_name='date_hatched',
        ),
    ]
