# Generated by Django 5.2 on 2025-04-07 14:41

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_date_discovered_petinstance_date_hatched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinstance',
            name='name',
            field=models.CharField(help_text='What name has been bestowed upon this blessed pet? Must be unique and cannot be changed. Letters and numbers only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed; no spaces, symbols etc.')]),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='What unique term has the great Oneiromancer chosen to refer to this species? Letters only.', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')]),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, help_text='How does this style (variation in physical appearance and colour) deviate from the natural look of the species?'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(help_text="All species have a 'natural' look. Some have different styles i.e. variations in physical appearance and colour. What would you call this style? Letters only.", max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical characters are allowed; no numbers, spaces, symbols etc.')]),
        ),
        migrations.AlterConstraint(
            model_name='combination',
            name='pets_combination_species_style_unique_together',
            constraint=models.UniqueConstraint(fields=('species', 'style'), name='pets_combination_species_style_unique_together', violation_error_message='Combination of Species and Style is not unique together.'),
        ),
        migrations.AlterConstraint(
            model_name='petinstance',
            name='pets_petinstance_name_not_blank',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_petinstance_name_not_blank', violation_error_message='PetInstance name must not be blank.'),
        ),
        migrations.AlterConstraint(
            model_name='petinstance',
            name='pets_petinstance_name_case_insensitive_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_petinstance_name_case_insensitive_unique', violation_error_message='PetInstance name already exists (case insensitive match).'),
        ),
        migrations.AlterConstraint(
            model_name='species',
            name='pets_species_name_not_blank',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_species_name_not_blank', violation_error_message='Species name must not be blank.'),
        ),
        migrations.AlterConstraint(
            model_name='species',
            name='pets_species_name_case_insensitive_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_species_name_case_insensitive_unique', violation_error_message='Species name already exists (case insensitive match).'),
        ),
        migrations.AlterConstraint(
            model_name='style',
            name='pets_style_name_not_blank',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pets_style_name_not_blank', violation_error_message='Style name must not be blank.'),
        ),
        migrations.AlterConstraint(
            model_name='style',
            name='pets_style_name_case_insensitive_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='pets_style_name_case_insensitive_unique', violation_error_message='Style name already exists (case insensitive match).'),
        ),
    ]
